# Generated by Django 4.2.2 on 2023-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.ImageField(default=0, upload_to='')),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('status', models.CharField(blank=True, default='Online', max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('auth_provider', models.CharField(blank=True, default='email', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
